name: Auto-merge

on:
  pull_request:
    types: [labeled, synchronize, opened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.mergeable == true
    steps:
      - uses: "peter-evans/enable-pull-request-automerge@v3"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
